--KORED.sql
DROP TABLE ANIMAL;
CREATE TABLE ANIMAL(
	ANO NUMBER(2) CONSTRAINT ANIMAL_ANO_PK PRIMARY KEY,
	ANAME VARCHAR2(30) NOT NULL,
	ATYPE VARCHAR2(30) NOT NULL,
	AGRADE VARCHAR2(20) NOT NULL,
	ADESC VARCHAR2(200)
);

DROP SEQUENCE ANO_SEQ;
CREATE SEQUENCE ANO_SEQ START WITH 1;
	
COMMIT;

